//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD.CRUD_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRUD_Service.ICRUD")]
    public interface ICRUD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/GetProducts", ReplyAction="http://tempuri.org/ICRUD/GetProductsResponse")]
        System.Collections.Generic.List<MVC_CRUD.Entities.Models.ProductEntity> GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/GetProducts", ReplyAction="http://tempuri.org/ICRUD/GetProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MVC_CRUD.Entities.Models.ProductEntity>> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/GetCategories", ReplyAction="http://tempuri.org/ICRUD/GetCategoriesResponse")]
        System.Collections.Generic.List<MVC_CRUD.Entities.Models.CategoryEntity> GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/GetCategories", ReplyAction="http://tempuri.org/ICRUD/GetCategoriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MVC_CRUD.Entities.Models.CategoryEntity>> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/GetSuppliers", ReplyAction="http://tempuri.org/ICRUD/GetSuppliersResponse")]
        System.Collections.Generic.List<MVC_CRUD.Entities.Models.SupplierEntity> GetSuppliers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/GetSuppliers", ReplyAction="http://tempuri.org/ICRUD/GetSuppliersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MVC_CRUD.Entities.Models.SupplierEntity>> GetSuppliersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/AddProducts", ReplyAction="http://tempuri.org/ICRUD/AddProductsResponse")]
        MVC_CRUD.Entities.Models.ProductEntity AddProducts(MVC_CRUD.Entities.Models.ProductEntity product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUD/AddProducts", ReplyAction="http://tempuri.org/ICRUD/AddProductsResponse")]
        System.Threading.Tasks.Task<MVC_CRUD.Entities.Models.ProductEntity> AddProductsAsync(MVC_CRUD.Entities.Models.ProductEntity product);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRUDChannel : MVC_CRUD.CRUD_Service.ICRUD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRUDClient : System.ServiceModel.ClientBase<MVC_CRUD.CRUD_Service.ICRUD>, MVC_CRUD.CRUD_Service.ICRUD {
        
        public CRUDClient() {
        }
        
        public CRUDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRUDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRUDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRUDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<MVC_CRUD.Entities.Models.ProductEntity> GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MVC_CRUD.Entities.Models.ProductEntity>> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public System.Collections.Generic.List<MVC_CRUD.Entities.Models.CategoryEntity> GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MVC_CRUD.Entities.Models.CategoryEntity>> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public System.Collections.Generic.List<MVC_CRUD.Entities.Models.SupplierEntity> GetSuppliers() {
            return base.Channel.GetSuppliers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MVC_CRUD.Entities.Models.SupplierEntity>> GetSuppliersAsync() {
            return base.Channel.GetSuppliersAsync();
        }
        
        public MVC_CRUD.Entities.Models.ProductEntity AddProducts(MVC_CRUD.Entities.Models.ProductEntity product) {
            return base.Channel.AddProducts(product);
        }
        
        public System.Threading.Tasks.Task<MVC_CRUD.Entities.Models.ProductEntity> AddProductsAsync(MVC_CRUD.Entities.Models.ProductEntity product) {
            return base.Channel.AddProductsAsync(product);
        }
    }
}
